# .github/workflows/deploy.yml
name: Deploy to Render
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.3
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }} # You'll need to add this in GitHub secrets
          api_key: ${{ secrets.RENDER_API_KEY }} # You'll need to add this in GitHub secrets
          clear_cache: true
