version: '3'
services:
  keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_ADMIN_URL=http://localhost:8080/auth
      - KC_HOSTNAME_URL=http://localhost:8080/auth
      - KC_HTTP_RELATIVE_PATH=/auth
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/keycloak-health-check.sh", "8080"]
      interval: 30s
      timeout: 10s
      retries: 3 