# This configuration is intended for development purpose
name: nextswift
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    build:
      context: .
      dockerfile: Dockerfile
    command: 'start-dev --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HTTP_PORT: 9080
      KC_HTTPS_PORT: 9443
      KC_HEALTH_ENABLED: true
      KC_HTTP_MANAGEMENT_PORT: 9990
    ports:
      - "9080:9080"
      - "9443:9443"
      - "9990:9990"
    healthcheck:
      test: ["CMD", "/opt/keycloak/health-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
