# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: nextswift
services:
  keycloak:
    build:
      context: .
      dockerfile: keycloak.Dockerfile
    command: "start-dev --http-enabled=true --hostname-strict=false --hostname=localhost"
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh

    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_HTTP_PORT=8080
      - KC_HTTPS_PORT=8443
      - KC_STATISTICS_ENABLED=true
      - KC_METRICS_ENABLED=true
    healthcheck:
      test: "bash /opt/keycloak/health-check.sh"
      interval: 5s
      timeout: 5s
      # Increased retries due to slow Keycloak startup in GitHub Actions using MacOS
      retries: 50
      start_period: 10s
    labels:
      org.springframework.boot.ignore: true
