# This configuration is intended for development purpose
name: nextswift
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command: 'start-dev --import-realm'
    volumes:
      - ./realm-config:/opt/keycloak/data/import:ro
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh:ro
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://c67okggoj39697.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d7soqlidsno04j
      KC_DB_USERNAME: u6kj4e3i1rcjlr
      KC_DB_PASSWORD: p96b27cb2e2cbaaf0d94d18ec3d764fa3034a871353ba86f07536e437c8a00001
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_FEATURES: scripts
      KC_HTTP_PORT: 8080
      KC_HTTPS_PORT: 8443
      KC_HEALTH_ENABLED: true
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8080:8080"
      - "8443:8443"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
