services:
  - type: web
    name: keycloak
    env: docker
    envVars:
      - name: KC_DB_URL_HOST
        value: roundhouse.proxy.rlwy.net
      - name: KC_DB_URL_PORT
        value: "25256"
      - name: KC_DB_URL_DATABASE
        value: railway
      - name: KC_DB_USERNAME
        value: postgres
      - name: KC_DB_PASSWORD
        value: DtuPFvzJPWTuGPZBTUCdIePiAXImqxPT
      - name: KC_DB_SCHEMA
        value: public
      - name: KC_HOSTNAME
        value: render-kc-gdz6.onrender.com
      - name: KC_HOSTNAME_ADMIN
        value: render-kc-gdz6.onrender.com
      - name: KC_HOSTNAME_URL
        value: https://render-kc-gdz6.onrender.com
      - name: KC_HOSTNAME_STRICT_BACKCHANNEL
        value: "false"
      - name: KC_HTTP_ENABLED
        value: "true"
