services:
  - type: web
    name: keycloak
    env: docker
    envVars:
      - name: KC_DB_URL_HOST
        value: roundhouse.proxy.rlwy.net
      - name: KC_DB_URL_PORT
        value: "25256"
      - name: KC_DB_URL_DATABASE
        value: railway
      - name: KC_DB_USERNAME
        value: postgres
      - name: KC_DB_PASSWORD
        value: DtuPFvzJPWTuGPZBTUCdIePiAXImqxPT
      - name: KC_DB_SCHEMA
        value: public
      - name: KEYCLOAK_ADMIN
        value: admin
      - name: KEYCLOAK_ADMIN_PASSWORD
        value: myKeycloakpa23
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HTTP_PORT
        value: "8080"
      - name: KC_HOSTNAME_URL
        value: https://render-kc-gdz6.onrender.com
      - name: KC_HOSTNAME_ADMIN_URL
        value: https://render-kc-gdz6.onrender.com
      - name: KC_PROXY
        value: passthrough
