services:
  - type: web
    name: keycloak
    runtime: docker
    dockerfilePath: ./keycloak.Dockerfile
    region: oregon
    plan: standard
    healthCheckPath: /health
    envVars:
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: POSTGRES_HOST
        sync: false
      - key: POSTGRES_DATABASE
        sync: false
      - key: POSTGRES_USER
        sync: false
      - key: POSTGRES_PASSWORD
        sync: false
