services:
  - type: web
    name: keycloak
    env: docker
    envVars:
      - name: KC_DB_URL
        value: jdbc:postgresql://roundhouse.proxy.rlwy.net:25256/railway
      - name: KC_DB_USERNAME
        value: postgres
      - name: KC_DB_PASSWORD
        value: DtuPFvzJPWTuGPZBTUCdIePiAXImqxPT
      - name: KC_DB_POOL_INITIAL_SIZE
        value: "5"
      - name: KC_DB_POOL_MIN_SIZE
        value: "5"
      - name: KC_DB_POOL_MAX_SIZE
        value: "50"
      - name: KC_HOSTNAME
        value: render-kc-gdz6.onrender.com
      - name: KC_PROXY
        value: edge
      - name: KC_HTTP_ENABLED
        value: "true"
      - name: KC_HTTP_PORT
        value: "8080"
